#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="${OUTPUT_FILE:-${ROOT_DIR}/.env.digitalocean.local}"

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required environment variable: ${name}" >&2
    exit 1
  fi
}

random_hex() {
  openssl rand -hex 32
}

require_env DOMAIN
require_env OBJECT_STORAGE_BUCKET
require_env OBJECT_STORAGE_ACCESS_KEY_ID
require_env OBJECT_STORAGE_SECRET_ACCESS_KEY

OBJECT_STORAGE_REGION="${OBJECT_STORAGE_REGION:-blr1}"
OBJECT_STORAGE_ENDPOINT_URL="${OBJECT_STORAGE_ENDPOINT_URL:-https://${OBJECT_STORAGE_REGION}.digitaloceanspaces.com}"
POSTGRES_DB="${POSTGRES_DB:-scanner_db}"
POSTGRES_USER="${POSTGRES_USER:-scanner_user}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(random_hex)}"
WORKER_TOKEN="${WORKER_TOKEN:-$(random_hex)}"
SECRET_KEY="${SECRET_KEY:-$(random_hex)}"
ENCRYPTION_KEY="${ENCRYPTION_KEY:-$(random_hex)}"
AI_BASE_URL="${AI_BASE_URL:-http://your-model-host:11434/v1}"
AI_MODEL="${AI_MODEL:-llama3.1}"
AI_API_KEY="${AI_API_KEY:-local-model}"

cat > "${OUTPUT_FILE}" <<EOF
DOMAIN=${DOMAIN}
ALLOWED_HOSTS=${DOMAIN}
CORS_ORIGINS=https://${DOMAIN}
BACKEND_BIND_ADDRESS=${BACKEND_BIND_ADDRESS:-127.0.0.1}
BACKEND_PORT=${BACKEND_PORT:-8000}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

QUEUE_BACKEND=postgres
SCAN_JOB_INLINE_WORKER=false
WORKER_AUTH_REQUIRED=true
WORKER_TOKEN=${WORKER_TOKEN}
SCAN_JOB_TIMEOUT_MINUTES=${SCAN_JOB_TIMEOUT_MINUTES:-20}
SCAN_WORKER_ID=${SCAN_WORKER_ID:-do-scan-worker-1}
SCAN_WORKER_POLL_INTERVAL=${SCAN_WORKER_POLL_INTERVAL:-10}
SCHEDULER_WORKER_ID=${SCHEDULER_WORKER_ID:-do-scheduler-worker-1}
WORKER_HEARTBEAT_INTERVAL=${WORKER_HEARTBEAT_INTERVAL:-15}
WORKER_HEARTBEAT_STALE_SECONDS=${WORKER_HEARTBEAT_STALE_SECONDS:-45}

OBJECT_STORAGE_PROVIDER=digitalocean-spaces
OBJECT_STORAGE_ENDPOINT_URL=${OBJECT_STORAGE_ENDPOINT_URL}
OBJECT_STORAGE_REGION=${OBJECT_STORAGE_REGION}
OBJECT_STORAGE_BUCKET=${OBJECT_STORAGE_BUCKET}
OBJECT_STORAGE_ACCESS_KEY_ID=${OBJECT_STORAGE_ACCESS_KEY_ID}
OBJECT_STORAGE_SECRET_ACCESS_KEY=${OBJECT_STORAGE_SECRET_ACCESS_KEY}
OBJECT_STORAGE_PREFIX=${OBJECT_STORAGE_PREFIX:-cloudguard/evidence}

AI_BASE_URL=${AI_BASE_URL}
AI_MODEL=${AI_MODEL}
AI_API_KEY=${AI_API_KEY}

OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_AGENT_MODEL=${OPENAI_AGENT_MODEL:-}

SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF

chmod 600 "${OUTPUT_FILE}"
echo "Wrote ${OUTPUT_FILE}"
